# Generated by Django 4.2.16 on 2024-11-13 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_answer_likes_question_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='likes',
        ),
    ]
