# Generated by Django 4.2.16 on 2024-11-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_question_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='likes',
            field=models.ManyToManyField(through='app.QuestionLike', to='app.like'),
        ),
    ]
