# Generated by Django 4.2.16 on 2024-11-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_answer_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='likes',
            field=models.ManyToManyField(through='app.AnswerLike', to='app.like'),
        ),
    ]
